[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v3-core=lib/v3-core/",
  "@aave/=lib/protocol-v2/",
  "lib/v2-periphery/=lib/v2-periphery/",
  "lib/v3-periphery/=lib/v3-periphery/"
]
